.github/workflows/ctest.yml, include/builtin.h, libft/CMakeLists.txt, libft/stdio/ft_dprintf/ft_dprintf.c, src/builtin/builtin_internal.h, src/builtin/echo.c, src/builtin/error.c, test/CMakeLists.txt, test/builtin_echo.cpp
=> builtin/echo: エラーメッセージの表示

include/builtin.h, libft/test/CMakeLists.txt, src/builtin/builtin_internal.h, src/builtin/get_next_option.c, src/builtin/unset.c, test/CMakeLists.txt, test/builtin_unset.cpp, test/get_next_option.cpp
=> builtin: unset

src/builtin/env.c, test/builtin_env.cpp
=> 値が未定義の変数はenvで表示しない

include/ast.h
=> define AST structures

.github/workflows/ctest.yml, .gitmodules, CMakeLists.txt, Makefile, compile_flags.txt, src/main.c, tests/CMakeLists.txt
readlineをsubmoduleとして管理. 適切にビルド, リンクされるようにした.
プロンプトを表示する簡単なmainも書いた.
=> Introduce readline

src/utils/list.c
=> fix double-free in command execution

src/exec/exec_internal.h, src/exec/execvp.c, src/exec/handle_command.c
細かい部分まで bash と完全一致しているわけではないが (issue 参照), 対応した.
close #44
=> display errors if command execution fails

src/exec/handle_command.c
=> resolve redirect-only execution issue

src/builtins/builtins_internal.h, src/builtins/echo.c, src/builtins/get_next_option.c, src/builtins/utils_internal.c, tests/get_next_option.cpp
`get_next_option` の実装が微妙だったので, 一部挙動の見直しもしつつリファクタした.
ついでに, `echo` の実装で使うようにした.
=> refactor `get_next_option`

src/main.c
=> parse and execute

src/parser/here_doc.c
=> add strdup filename

src/exec/exec_internal.h, src/exec/execute_ast.c, src/exec/handle_subshell.c, tests/execute_ast.cpp
=> support subshell

Makefile
- "-Wl,-no_compact_unwind" は Mac 環境のみ付ける
- リンクの順序をいい感じに
- その他細かい微調整
close #83
=> Update makefile build config

include/ast.h, include/token.h, src/exec/exec_internal.h, src/exec/execute_ast.c, src/exec/handle_semicolon.c, src/lexer/get_next_token.c, src/parser/command.c, src/parser/complete_command.c, src/parser/parse.c, src/parser/parser_internal.h, src/parser/utils_internal.c, tests/execute_ast.cpp, tests/lexer.cpp, tests/parser.cpp
=> Support semicolon

include/variables.h, src/builtins/export/export_each_arg.c, src/variables/parse.c, tests/parse_variable_assignment.cpp
気に食わない部分を直したのと, heap-buffer-overflow を直した.
=> refactor parse assignment

src/init/init_shell.c, src/main.c
`^D` で余計な改行を出してたのも直しちゃった.
close #91
=> fix shell name

tests/CMakeLists.txt
=> fix cmake build settings

src/parser/word_expansion/expand_parameters_utils.c, tests/word_expansion.cpp
=> expand last_exit_status

src/parser/here_doc.c, src/parser/parser_internal.h, src/parser/word_expansion/expand_parameters.c, src/parser/word_expansion/expand_word.c, src/parser/word_expansion/remove_quotes.c, src/parser/word_expansion/word_expansion_internal.h, tests/word_expansion.cpp
=> heredoc周りの修正

file.c, src/builtins/cd/cd.c
=> handle empty string as an error in cd builtin command
